### ISSUE TITLE
Expose function to mark expired token as refreshed

### ISSUE THREAD

**Issue by brno32** [gustavo0197/react-jwt#2]
In my code, I check if the token is expired and then call my refresh endpoint if so. It'd be useful if there was a way to update the state inside `useJwt` to reevaluate the token after refresh so that `isExpired` would re-render as `true` and my code could proceed normally.

I could take a crack at it in a PR if that'd be welcome

**Comment by gustavo0197** [comment]
Hi, I just added a new method that you can use to refresh the useJwt's state, it is named "refreshToken()"

**Comment by brno32** [comment]
Thanks! that worked well for me.

I think `refreshToken` is a misleading name, as it does not actually refresh the token, but re-evaluates its validity. In my own code I've named it `reEvaluatedToken`

```typescript
const { isExpired, refreshToken: reEvaluateToken } = useJwt(token);
```
