### ISSUE TITLE
Need support for react 18

### ISSUE THREAD

**Issue by krish512** [gustavo0197/react-jwt#30]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/6457418/166097286-9fe95afa-82c6-49f0-b048-1d9e86b5f4d4.png">

**Comment by IonVillarreal** [comment]
any update? 👀

**Comment by gustavo0197** [comment]
Hi, I just added support for React v18. [Version 1.1.6](https://www.npmjs.com/package/react-jwt/v/1.1.6) should work with React 18
