### ISSUE TITLE
 window.atob fail to excute when 2 or more ('_') include in paload 

### ISSUE THREAD

**Issue by HThandarcho** [gustavo0197/react-jwt#52]
const base64: string = payload.replace("-", "+").replace("_", "/") + padding;
    const jsonPayload = decodeURIComponent(
      window.atob(base64)
          .split('')
          .map(c => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2))
          .join('')
    );
[window.atob(base64)] this line gives me an error :【code: 5
   message:'Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.'
   name:'InvalidCharacterError'】
★reason: when paload's value include 2 or more ('_') then above error occur.

**Comment by gustavo0197** [comment]
- Can you decode the jwt in jwt.io?
- Could you provide a jwt example?

**Comment by HThandarcho** [comment]
@gustavo0197 
Hi
I can decode to jwt in jwt.io.
My jwt data contains private information, so I can't share in here.
Note: decoded jwt data contains japanese words..

**Comment by HThandarcho** [comment]
> * Can you decode the jwt in jwt.io?
> * Could you provide a jwt example?

I can decode to jwt in jwt.io.
Please reply me after ur checking...

this is sample jwt,
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.U0_li5XkvZzmpJzoqLwiLCJmaXJzdE5hbWUiOiJTU0_li5XkvZzmpJzoqLwiLCJsYXN0TmFtZSI6IkIsImlh

**Comment by gustavo0197** [comment]
Hi, thank you, I will try to fix it

**Comment by gustavo0197** [comment]
It looks like the provided JWT's payload is not a valid JSON object. If I create a valid JWT that contains japanese words I'm not getting this error.

Which version of react-jwt do you have installed?

**Comment by HThandarcho** [comment]
Hello @gustavo0197 
Thanks for your confirm.

I used latest ver of react-jwt  version : 1.1.8
jwt that I sent last week is not included private key part, so I made new sample jwt.

sample jwt as below
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlNTT0B0ZXMub25taWNyb3NvZnQuY29tIiwiZGlzcGxheU5hbWUiOiJTU0_li5XkvZzmpJzoqLwiLCJmaXJzdE5hbWUiOiJTU0_li5XkvZzmpJzoqLwiLCJsYXN0TmFtZSI6IlNPIiwiaWF0IjoxNjg0MTI4NTMyLCJleHAiOjE2ODQxMjg3MTJ9.IHruBwxpwjPJ5Frj0iOzG_l-njPSYktKgkVOw02QFpA'

**Comment by HThandarcho** [comment]
> It looks like the provided JWT's payload is not a valid JSON object. If I create a JWT that contains japanese words I'm not getting this error.
> 
> Which version of react-jwt do you have installed?
Thanks for your confirm.

I used latest ver of react-jwt version : 1.1.8
jwt that I sent last week is not included private key part, so I made new sample jwt.

sample jwt as below
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlNTT0B0ZXMub25taWNyb3NvZnQuY29tIiwiZGlzcGxheU5hbWUiOiJTU0_li5XkvZzmpJzoqLwiLCJmaXJzdE5hbWUiOiJTU0_li5XkvZzmpJzoqLwiLCJsYXN0TmFtZSI6IlNPIiwiaWF0IjoxNjg0MTI4NTMyLCJleHAiOjE2ODQxMjg3MTJ9.IHruBwxpwjPJ5Frj0iOzG_l-njPSYktKgkVOw02QFpA'

**Comment by HThandarcho** [comment]
@gustavo0197 
I used latest ver of react-jwt 1.1.8.
Please check below jwt .

here is valid sample jwt
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlNTT0B0ZXMub25taWNyb3NvZnQuY29tIiwiZGlzcGxheU5hbWUiOiJTU0_li5XkvZzmpJzoqLwiLCJmaXJzdE5hbWUiOiJTU0_li5XkvZzmpJzoqLwiLCJsYXN0TmFtZSI6IlNPIiwiaWF0IjoxNjg0MTI4NTMyLCJleHAiOjE2ODQxMjg3MTJ9.IHruBwxpwjPJ5Frj0iOzG_l-njPSYktKgkVOw02QFpA'

**Comment by gustavo0197** [comment]
@HThandarcho  I released a new version (v1.2.0). Seems like it is working fine

**Comment by HThandarcho** [comment]
@gustavo0197 Oh Thanks a lot for your support , I'll update .

**Comment by HThandarcho** [comment]
This issue has been solved by latest ver -1.2.0.
